# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\x0cLoginRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x10\n\x0eLogoutResponse\" \n\rStreamRequest\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x89\x03\n\x0eStreamResponse\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0c\x63lient_login\x18\x02 \x01(\x0b\x32\x1a.chat.StreamResponse.LoginH\x00\x12\x34\n\rclient_logout\x18\x03 \x01(\x0b\x32\x1b.chat.StreamResponse.LogoutH\x00\x12\x36\n\x0e\x63lient_message\x18\x04 \x01(\x0b\x32\x1c.chat.StreamResponse.MessageH\x00\x12\x38\n\x0fserver_shutdown\x18\x05 \x01(\x0b\x32\x1d.chat.StreamResponse.ShutdownH\x00\x1a\x15\n\x05Login\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x16\n\x06Logout\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a(\n\x07Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a\n\n\x08ShutdownB\x07\n\x05\x65vent2\xac\x01\n\x04\x43hat\x12\x32\n\x05Login\x12\x12.chat.LoginRequest\x1a\x13.chat.LoginResponse\"\x00\x12\x35\n\x06Logout\x12\x13.chat.LogoutRequest\x1a\x14.chat.LogoutResponse\"\x00\x12\x39\n\x06Stream\x12\x13.chat.StreamRequest\x1a\x14.chat.StreamResponse\"\x00(\x01\x30\x01\x42!Z\x1fgithub.com/brunsgaard/lets-chatb\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_LOGOUTREQUEST = DESCRIPTOR.message_types_by_name['LogoutRequest']
_LOGOUTRESPONSE = DESCRIPTOR.message_types_by_name['LogoutResponse']
_STREAMREQUEST = DESCRIPTOR.message_types_by_name['StreamRequest']
_STREAMRESPONSE = DESCRIPTOR.message_types_by_name['StreamResponse']
_STREAMRESPONSE_LOGIN = _STREAMRESPONSE.nested_types_by_name['Login']
_STREAMRESPONSE_LOGOUT = _STREAMRESPONSE.nested_types_by_name['Logout']
_STREAMRESPONSE_MESSAGE = _STREAMRESPONSE.nested_types_by_name['Message']
_STREAMRESPONSE_SHUTDOWN = _STREAMRESPONSE.nested_types_by_name['Shutdown']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LogoutRequest)
  })
_sym_db.RegisterMessage(LogoutRequest)

LogoutResponse = _reflection.GeneratedProtocolMessageType('LogoutResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTRESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.LogoutResponse)
  })
_sym_db.RegisterMessage(LogoutResponse)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.StreamRequest)
  })
_sym_db.RegisterMessage(StreamRequest)

StreamResponse = _reflection.GeneratedProtocolMessageType('StreamResponse', (_message.Message,), {

  'Login' : _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), {
    'DESCRIPTOR' : _STREAMRESPONSE_LOGIN,
    '__module__' : 'chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Login)
    })
  ,

  'Logout' : _reflection.GeneratedProtocolMessageType('Logout', (_message.Message,), {
    'DESCRIPTOR' : _STREAMRESPONSE_LOGOUT,
    '__module__' : 'chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Logout)
    })
  ,

  'Message' : _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
    'DESCRIPTOR' : _STREAMRESPONSE_MESSAGE,
    '__module__' : 'chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Message)
    })
  ,

  'Shutdown' : _reflection.GeneratedProtocolMessageType('Shutdown', (_message.Message,), {
    'DESCRIPTOR' : _STREAMRESPONSE_SHUTDOWN,
    '__module__' : 'chat_pb2'
    # @@protoc_insertion_point(class_scope:chat.StreamResponse.Shutdown)
    })
  ,
  'DESCRIPTOR' : _STREAMRESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.StreamResponse)
  })
_sym_db.RegisterMessage(StreamResponse)
_sym_db.RegisterMessage(StreamResponse.Login)
_sym_db.RegisterMessage(StreamResponse.Logout)
_sym_db.RegisterMessage(StreamResponse.Message)
_sym_db.RegisterMessage(StreamResponse.Shutdown)

_CHAT = DESCRIPTOR.services_by_name['Chat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037github.com/brunsgaard/lets-chat'
  _LOGINREQUEST._serialized_start=53
  _LOGINREQUEST._serialized_end=99
  _LOGINRESPONSE._serialized_start=101
  _LOGINRESPONSE._serialized_end=131
  _LOGOUTREQUEST._serialized_start=133
  _LOGOUTREQUEST._serialized_end=163
  _LOGOUTRESPONSE._serialized_start=165
  _LOGOUTRESPONSE._serialized_end=181
  _STREAMREQUEST._serialized_start=183
  _STREAMREQUEST._serialized_end=215
  _STREAMRESPONSE._serialized_start=218
  _STREAMRESPONSE._serialized_end=611
  _STREAMRESPONSE_LOGIN._serialized_start=503
  _STREAMRESPONSE_LOGIN._serialized_end=524
  _STREAMRESPONSE_LOGOUT._serialized_start=526
  _STREAMRESPONSE_LOGOUT._serialized_end=548
  _STREAMRESPONSE_MESSAGE._serialized_start=550
  _STREAMRESPONSE_MESSAGE._serialized_end=590
  _STREAMRESPONSE_SHUTDOWN._serialized_start=592
  _STREAMRESPONSE_SHUTDOWN._serialized_end=602
  _CHAT._serialized_start=614
  _CHAT._serialized_end=786
# @@protoc_insertion_point(module_scope)
